version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:15.6
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    build: ./backend/
    env_file: .env
    depends_on:
      - db
    volumes: 
      - static:/backend_static
      - media:/media
  frontend:
    build: ./frontend/
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  nginx:
    build: ./infra/
    ports:
      - 9000:80
    volumes:
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static:/static
      - media:/media
    depends_on:
      - backend