# Generated by Django 4.2.10 on 2024-02-21 20:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0003_composition_recipe_composition_recipe"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Composition",
            new_name="Quantity",
        ),
    ]
