# Generated by Django 4.2.10 on 2024-02-21 07:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_follow_follow_prevent_self_follow_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="follow",
            name="prevent_self_follow",
        ),
        migrations.AddConstraint(
            model_name="follow",
            constraint=models.CheckConstraint(
                check=models.Q(("user", models.F("author")), _negated=True),
                name="prevent_self_follow",
                violation_error_message="Нельзя подписаться на самого себя",
            ),
        ),
    ]
